// <auto-generated />
using System;
using LearningCenter.Persistence.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearningCenter.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231103120404_Location and other migrations")]
    partial class Locationandothermigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearningCenter.Domain.Entities.Common.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Common.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Common.Identity.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDarkModeEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Common.Location.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77589501-22b7-4fa2-9436-534c0c46913e"),
                            Name = "Uzbekistan",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("33517080-5e99-4591-b85d-2ed1ebf3bd98"),
                            Name = "Tashkent",
                            ParentId = new Guid("77589501-22b7-4fa2-9436-534c0c46913e"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("5eccba7f-4361-4ee6-832f-35ab309786cd"),
                            Name = "Navoiy",
                            ParentId = new Guid("77589501-22b7-4fa2-9436-534c0c46913e"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Courses.CourseStudent", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId1")
                        .HasColumnType("uuid");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId1");

                    b.ToTable("CourseStudents");
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Common.Identity.UserRole", b =>
                {
                    b.HasOne("LearningCenter.Domain.Entities.Common.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("LearningCenter.Domain.Entities.Common.Identity.UserRole", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Common.Identity.UserSettings", b =>
                {
                    b.HasOne("LearningCenter.Domain.Entities.Common.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("LearningCenter.Domain.Entities.Common.Identity.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Common.Location.LocationEntity", b =>
                {
                    b.HasOne("LearningCenter.Domain.Entities.Common.Location.LocationEntity", "ParentLocation")
                        .WithMany("ChildrenLocations")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Courses.Course", b =>
                {
                    b.HasOne("LearningCenter.Domain.Entities.Common.Identity.User", "Teacher")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Courses.CourseStudent", b =>
                {
                    b.HasOne("LearningCenter.Domain.Entities.Courses.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningCenter.Domain.Entities.Common.Identity.User", "Student")
                        .WithMany("CourseStudents")
                        .HasForeignKey("StudentId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Common.Identity.User", b =>
                {
                    b.Navigation("CourseStudents");

                    b.Navigation("TeacherCourses");
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Common.Location.LocationEntity", b =>
                {
                    b.Navigation("ChildrenLocations");
                });

            modelBuilder.Entity("LearningCenter.Domain.Entities.Courses.Course", b =>
                {
                    b.Navigation("CourseStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
